services:

  cache:
    image: redis:7.0.2-alpine
    # ports:
    #   - '6379:6379'
    # restart: always
    env_file:
      - .env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15.1-alpine
    # ports:
    #   - '5432:5432'
    # restart: always
    env_file:
      - .env
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  web:
    image: ctezlifrn/moodle
    build: .
    ports:
      - '8080:80'
    env_file:
      - .env
    volumes:
      - './volumes/moodledata:/var/moodledata'
    command: apache2-foreground
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  cron:
    image: ctezlifrn/moodle
    build: .
    env_file:
      - .env
    volumes:
      - './volumes/moodledata:/var/moodledata'
      - './volumes/moodlelog:/var/custom_log'
    command: exec-cron.sh
    depends_on:
      db:
        condition: service_healthy
