#!/usr/bin/env bash
source _/functions

echo_info "Reset confs"
rm -rf ./confs/enabled
cp -r ./confs/examples ./confs/enabled

echo_info "Stop the world"
_/down

echo_info "Reset volumes"
sudo rm -rf volumes

mkdir -p volumes/ava01_moodledata && chmod 777 volumes/ava01_moodledata
mkdir -p volumes/ava02_moodledata && chmod 777 volumes/ava02_moodledata
